# seeds.yaml
# This file contains the list of static seeds to potentially use during experiments for training/hyper-optimizing GAE

seeds:
  - 42
  - 100
  - 123
  - 200
  - 300
  - 400
  - 500
  - 600
  - 700
  - 800
  - 900
  - 1000
  - 1100
  - 1200
  - 1300
  - 1400
  - 1500
  - 1600
  - 1700
  - 1800
  - 1900
  - 2000
  - 2100
  - 2200
