# Configuration file for the generation of the graphs

num_nodes_range: [10, 25]
num_services_range: [1, 3]
homogeneity_range: [0.1, 0.1] # do not go below 0.1 otherwise it goes to infinite and may crash
firewall_rule_incoming_probability_range: [0, 0] # probability there will be an incoming BLOCK rule on each protocol we are LISTENING on
firewall_rule_outgoing_probability_range: [0, 0] # probability there will be an outgoing BLOCK rule on each protocol
knows_neighbor_probability_range: [0.2, 0.8]
data_presence_probability_range: [0.2, 0.8]
partial_visibility_probability_range: [0.2, 0.8]
need_to_escalate_probability_range: [0.2, 0.8]
service_shutdown_probability_range: [0, 0]
success_rate_probability_range: [0.6, 1]
probing_detection_probability_range: [0, 0]
exploit_detection_probability_range: [0, 0]
value_range: [1, 100]

min_presence_each_category: 0.05
minimum_access_connectivity_threshold: 0.5
minimum_knows_connectivity_threshold: 0.5
minimum_dos_connectivity_threshold: 0.5
