on:
  workflow_dispatch: # Workflow dispatch allows manual triggering of the workflow
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12.4']
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Pull pip packages from cache
        uses: actions/cache@v3
        with:
          key: pip-"${{ runner.os }}"-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements.dev.txt') }}-${{ hashFiles('setup.py') }}
          restore-keys: pip-"${{ runner.os }}"

          path: ${{ env.pythonver.pythonLocation }}/lib/python3.10/site-packages

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.12.4'
          miniconda-version: "latest"
          activate-environment: ccyberbattlesim
          auto-activate-base: false
          environment-file: environment.yml

      - name: Conda info
        shell: bash -el {0}
        run: conda info
